# NumPy

## Load Dirty CSV

1. Wczytaj tekst z URL podanego na wejściu (patrz sekcja input)
1. Z pierwszej linii wybierz nazwy gatunków Irysów i zapisz rezultat jako ``species: ndarray``
1. W pozostałych linii:

    * Wczytaj kolumny z danymi i zapisz do ``features: ndarray``
    * Wczytaj ostatnią kolumnę z numerami gatunków i zapisz do ``labels: ndarray``

1. Wyświetl ``species``, ``labels`` i ``features``

In [1]:
import numpy as np

url = 'https://raw.githubusercontent.com/AstroMatt/book-python/master/numerical-analysis/numpy/data/iris-dirty.csv'

species = np.loadtxt(url, max_rows=1, delimiter=',', usecols=(2,3,4), dtype=str)
features = np.loadtxt(url, skiprows=1, delimiter=',', usecols=(0,1,2,3))
labels = np.loadtxt(url, skiprows=1, delimiter=',', usecols=(4))

## Array Create
1. Stwórz ``a: ndarray`` z liczbami parzystymi od 0 do 100
1. Liczby muszą być typu ``float``

In [2]:
## Results with ``%%timeit -n 1_000_000 -r 10``

np.arange(0, 100, step=2, dtype=float)
# 756 ns ± 10.3 ns per loop (mean ± std. dev. of 10 runs, 1000000 loops each)

np.array(range(0, 100, 2), dtype=float)
# 8.28 µs ± 364 ns per loop (mean ± std. dev. of 10 runs, 1000000 loops each)

np.array([x for x in range(0, 100) if x % 2 == 0], dtype=float)
# 9.76 µs ± 324 ns per loop (mean ± std. dev. of 10 runs, 1000000 loops each)

np.array([float(x) for x in range(0, 100) if x % 2 == 0])
# 12.7 µs ± 195 ns per loop (mean ± std. dev. of 10 runs, 1000000 loops each)

np.array([float(x) for x in range(0, 100, 2)])
# 8.35 µs ± 196 ns per loop (mean ± std. dev. of 10 runs, 1000000 loops each)

np.array([x for x in range(0, 100, 2)], dtype=float)
# 5.89 µs ± 77 ns per loop (mean ± std. dev. of 10 runs, 1000000 loops each)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.,
       52., 54., 56., 58., 60., 62., 64., 66., 68., 70., 72., 74., 76.,
       78., 80., 82., 84., 86., 88., 90., 92., 94., 96., 98.])

## Random Float

1. Ustaw ziarno losowości na zero
1. Wypisz ``ndarray`` z 10 losowymi liczbami zmiennoprzecinkowymi

In [3]:
np.random.seed(0)
np.random.random(size=10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

## Random Int

1. Ustaw ziarno losowości na zero
1. Print ``ndarray`` o rozmiarze 16x16 z losowymi liczbami całkowitymi ``<0,9>`` (włącznie)

In [4]:
np.random.seed(0)
np.random.randint(0, 10, size=(16, 16))

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4, 7, 6, 8, 8, 1, 6],
       [7, 7, 8, 1, 5, 9, 8, 9, 4, 3, 0, 3, 5, 0, 2, 3],
       [8, 1, 3, 3, 3, 7, 0, 1, 9, 9, 0, 4, 7, 3, 2, 7],
       [2, 0, 0, 4, 5, 5, 6, 8, 4, 1, 4, 9, 8, 1, 1, 7],
       [9, 9, 3, 6, 7, 2, 0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1, 5, 9, 3, 0, 5, 0],
       [1, 2, 4, 2, 0, 3, 2, 0, 7, 5, 9, 0, 2, 7, 2, 9],
       [2, 3, 3, 2, 3, 4, 1, 2, 9, 1, 4, 6, 8, 2, 3, 0],
       [0, 6, 0, 6, 3, 3, 8, 8, 8, 2, 3, 2, 0, 8, 8, 3],
       [8, 2, 8, 4, 3, 0, 4, 3, 6, 9, 8, 0, 8, 5, 9, 0],
       [9, 6, 5, 3, 1, 8, 0, 4, 9, 6, 5, 7, 8, 8, 9, 2],
       [8, 6, 6, 9, 1, 6, 8, 8, 3, 2, 3, 6, 3, 6, 5, 7],
       [0, 8, 4, 6, 5, 8, 2, 3, 9, 7, 5, 3, 4, 5, 3, 3],
       [7, 9, 9, 9, 7, 3, 2, 3, 9, 7, 7, 5, 1, 2, 2, 8],
       [1, 5, 8, 4, 0, 2, 5, 5, 0, 8, 1, 1, 0, 3, 8, 8],
       [4, 4, 0, 9, 3, 7, 3, 2, 1, 1, 2, 1, 4, 2, 5, 5]])

## Random Sample

1. Ustaw ziarno losowości na zero
1. Wyświetl 6 losowych i nie powtarzających się liczb całkowitych z zakresu od 1 do 49.

In [5]:
np.random.seed(0)
np.random.choice(np.arange(1,49), 6, replace=False)

array([30,  5, 27, 31, 33, 38])

## As Type

1. Dany ``a: ndarray`` (patrz sekcja input)
1. Przekonwertuj do typu ``int``
1. Rezultat rzutuj na typ ``bool``
1. Co się stało w każdym z tych kroków?

In [6]:
a = np.array([[-1.1, 0.0, 1.1],
              [ 2.2, 3.3, 4.4]])

In [7]:
a.astype(int)

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [8]:
a.astype(bool)

array([[ True, False,  True],
       [ True,  True,  True]])

## Array Attributes

1. Ustaw ziarno losowości na zero.
1. Stwórz ``a: ndarray`` o rozmiarze 16x16.
1. Struktura musi zawierać losowe liczby (0-9).
1. Wypisz liczbę:

    * wymiarów,
    * kolumn,
    * wierszy,
    * ilość elementów.


In [9]:
a = np.random.randint(0, 10, size=(16, 16))

print('Ndim:', a.ndim)
print('Size:', a.size)
print('Dtype:', a.dtype)
print('Itemsize:', a.itemsize)
print('Shape:', a.shape)
print('Strides:', a.strides)

Ndim: 2
Size: 256
Dtype: int64
Itemsize: 8
Shape: (16, 16)
Strides: (128, 8)


## Shape

1. Dany ``a: ndarray`` (patrz sekcja input)
1. Spłaszcz używając metody ``.ravel()``
1. Wypisz ``a``
1. Zmień kształt na powrót na 3x3
1. Wypisz ``a``

In [10]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [11]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexing

1. Stwórz ``output: ndarray``
1. Dodaj do ``output`` elementy z ``INPUT`` (patrz sekcja input) o indeksach:

    - wiersz 0, kolumna 2
    - wiersz 2, kolumna 2
    - wiersz 0, kolumna 0
    - wiersz 1, kolumna 0

1. Rozmiar ``output`` musi być 2x2
1. Typ ``output`` musi być float

In [13]:
INPUT = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [14]:
np.array([
    INPUT[0,2],
    INPUT[2,2],
    INPUT[0,0],
    INPUT[1,2],
], dtype=float).reshape(2, 2)

array([[3., 9.],
       [1., 6.]])

## Array Slicing

1. Użyj wejściowej ndarray (patrz sekcja input)
1. Wyisz wewnętrzne 2x2 elementy

In [15]:
INPUT = np.array([
    [2, 8, 1, 5],
    [8, 8, 4, 4],
    [5, 5, 2, 5],
    [1, 0, 6, 0],
])

In [16]:
INPUT[1:3, 1:3]

array([[8, 4],
       [5, 2]])

## Sum of inner elements

1. Użyj tylko funkcji z modułu ``random`` biblioteki ``numpy``
1. Ustaw ziarno losowości na zero
1. Wygeneruj ``INPUT: ndarray`` z 16x16 losowych cyfr (0-9 włącznie)
1. Policz sumę środkowych 4x4 elementów
1. Środkowa macierz jest dokładnie w środku większej

In [17]:
np.random.seed(0)


a = np.random.randint(0, 10, size=(16, 16))
b = a[6:-6, 6:-6]

print(b.sum())

75


In [18]:
np.random.seed(0)

NUM_X = 16
NUM_Y = 16
INNER_X = 4
INNER_Y = 4


a = np.random.randint(0, 10, size=(NUM_X, NUM_Y))

margines_x = int((NUM_X - INNER_X) / 2)
margines_y = int((NUM_Y - INNER_Y) / 2)
a[margines_x:-margines_x, margines_y:-margines_y].sum()

75

## Array Iteration

1. Dany ``a: ndarray`` (patrz sekcja input)
1. Używając ``for`` iteruj po ``INPUT``
1. Wypisz liczby parzyste

In [19]:
INPUT = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [20]:
for num in INPUT.ravel():
    if num % 2 == 0:
        print(num)

2
4
6
8


## Clip

1. Ustaw ziarno losowości na zero
1. Wygeneruj ``a: ndarray`` z 21 losowymi liczbami całkowitymi od 0 do 100 (rozłącznie)
1. Zmień kształt na 7x3
1. Przytnij liczby w pierwszej kolumnie od 50 (włącznie) do 80 (rozłącznie)
1. Wypisz ``a``

In [21]:
np.random.seed(0)

a = np.random.randint(0, 100, size=21).reshape(7, 3)
a

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58],
       [65, 39, 87],
       [46, 88, 81]])

In [22]:
a[:, 0] = a[:, 0].clip(50, 80)
a

array([[50, 47, 64],
       [67, 67,  9],
       [80, 21, 36],
       [80, 70, 88],
       [80, 12, 58],
       [65, 39, 87],
       [50, 88, 81]])

## Array Methods

1. Ustaw ziarno losowości na zero
1. Wygeneruj ``a: ndarray`` z 12 losowymi liczbami całkowitymi od 0 do 100 (rozłącznie)
1. Zmień kształt na 3x4
1. Transponuj ``a``
1. Wypisz ``a``

In [23]:
np.random.seed(0)

a = np.random.randint(0, 100, size=12).reshape(3, 4)
a.sort(axis=-1)  # a.sort(axis=1)
a.transpose()

array([[44,  9, 36],
       [47, 21, 70],
       [64, 67, 87],
       [67, 83, 88]])

## Arithmetic operations

1. Dla danych: ``a: ndarray``, ``b: ndarray``, ``c: ndarray`` (patrz sekcja input)
1. Oblicz pierwiastek kwadratowy każdego z elementu w ``a`` i ``b``
1. Oblicz drugą potęgę (kwadrat) każdego z elementu w ``c``
1. Dodaj elementy z ``a`` do ``b``
1. Przemnóż wynik przez ``c``

In [24]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)

In [25]:
a = np.sqrt(a)
b = np.sqrt(b)
c = np.power(c, 2)

(a + b) * c

array([[ 1.41421356,  2.73205081],
       [45.254834  ,  0.        ]])

## Array Addition

1. Dodaj ``a`` i ``b``
1. Dodaj ``b`` i ``a``
1. Co się stało?

In [26]:
a = np.array([[1, 0], [0, 1]])
b = [[4, 1], [2, 2]]

In [27]:
a + b

array([[5, 1],
       [2, 3]])

In [28]:
b + a

array([[5, 1],
       [2, 3]])

## Array Multiplication

1. Dla danych: ``a: ndarray``, ``b: ndarray`` (patrz sekcja input)
1. Przemnóż ``a`` i ``b`` używając mnożenia skalarnego
1. Przemnóż ``a`` i ``b`` używając mnożenia macierzowego
1. Przemnóż ``b`` i ``a`` używając mnożenia skalarnego
1. Przemnóż ``b`` i ``a`` używając mnożenia macierzowego
1. Omów wyniki

In [29]:
a = np.array([[1,0,1,0],
              [0,1,1,0],
              [3,2,1,0],
              [4,1,2,0]])

b = np.array([[4,1],
              [2,2],
              [5,1],
              [2,3]])

In [30]:
a * b

ValueError: operands could not be broadcast together with shapes (4,4) (4,2) 

In [31]:
a @ b

array([[ 9,  2],
       [ 7,  3],
       [21,  8],
       [28,  8]])

In [32]:
b * a

ValueError: operands could not be broadcast together with shapes (4,2) (4,4) 

In [33]:
b @ a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

## Array Concatenation

1. Dane są jednowymiarowe: ``a: ndarray``, ``b: ndarray`` (patrz sekcja input)
1. Połącz je ze sobą
1. Przedstaw wynik jako ``ndarray``: dwa wiersze na trzy kolumny

In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b)).reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

## Array Logic

1. Ustaw ziarno losowości na zero
1. Wygeneruj ``a: ndarray`` z 9 losowymi liczbami całkowitymi od 0 do 100 (rozłącznie)
1. Sprawdź parzyste elementy, które są mniejsze od 50
1. Sprawdź czy wszystkie liczby spełniają ten warunek
1. Sprawdź czy jakakolwiek liczba spełnia ten warunek

In [35]:
np.random.seed(0)

a = np.random.randint(0, 100, size=9)
b = np.logical_and(a % 2, a < 50)

print('Any:', b.any())
print('All:', b.all())

Any: True
All: False


## Is in Array

1. Ustaw ziarno losowości na zero
1. Wygeneruj ``a: ndarray`` z 50 losowymi liczbami całkowitymi od 0 do 100 (rozłącznie)
1. Wygeneruj ``b: ndarray`` z kolejnymi potęgami liczby 2, wykładnik od 0 do 6 (włącznie)
1. Sprawdź, które elementy z ``a`` są obecne w ``b``

In [36]:
np.random.seed(0)

a = np.random.randint(0, 100, size=50)
b = 2 ** np.arange(7)

np.isin(a, b)

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
        True, False, False, False, False])

## Array Select

1. Ustaw ziarno losowości na 0
1. Wygeneruj ``a: ndarray`` rozmiaru 50x50
1. ``a`` musi zawierać losowe liczby całkowite z zakresu od 0 do 1024 włącznie
1. Stwórz ``b: ndarray`` z elementami wybranymi z ``a``, które są potęgami dwójki
1. Posortuj ``b`` w kolejności malejącej
1. Wypisz ``b``

In [37]:
np.random.seed(0)

MIN = 0
MAX = 1025
SIZE = (50, 50)
SELECT = 2 ** np.arange(11)


a = np.random.randint(MIN, MAX, size=SIZE)
b = a[np.isin(a, SELECT)]
b.sort()
np.flip(b)

array([1024, 1024, 1024, 1024, 1024, 1024,  512,  512,  512,  512,  256,
        256,  256,  256,  256,  128,  128,  128,  128,  128,   64,   32,
         32,   32,   32,   32,   16,   16,   16,   16,   16,   16,    8,
          8,    4,    2,    2,    2,    2,    2])

## Trigonometry

1. Program wczytuje od użytkownika wielkość kąta w stopniach
1. Użytkownik zawsze podaje ``int`` albo ``float``
1. Wyświetl wartość funkcji trygonometrycznych (sin, cos, tg, ctg)
1. Ctg dla wartości 180 stopni nie istnieje
1. Jeżeli funkcja trygonometryczna nie istnieje dla danego kąta podnieś stosowny wyjątek

In [ ]:
angle = input('Type angle [deg]: ')
angle = float(angle)


class CtgDoesNotExistsError(Exception):
    pass


if angle == 180:
    raise CtgDoesNotExistsError('Ctg for 180 does not exists')

    
angle = np.deg2rad(angle)

print('Sin', np.sin(angle))
print('Cos', np.cos(angle))
print('Tan', np.tan(angle))
print('Ctg', 1 / np.tan(angle))

## Polynomial Polyfit

1. Dla danych punktów (patrz sekcja input)
1. Odseparuj pierwszy wiersz (nagłówek) do danych
1. Oblicz współczynniki najlepiej dopasowanego wielomianu 3 stopnia

In [ ]:
INPUT = [
    ('x', 'y'),
    (-4.0, 0.0),
    (-3.0, 2.5),
    (-2.0, 2.0),
    (0.0, -2.0),
    (2.0, 0.0),
    (3.0, 7.0), 
]

In [ ]:
header, *data = INPUT

x = [x for x,y in data]
y = [y for x,y in data]

np.polyfit(x, y, deg=3)

## Euclidean distance 2D

1. Dane są dwa punkty ``A: Tuple[int, int]`` i ``B: Tuple[int, int]``
1. Koordynaty są w systemie kartezjańskim
1. Punkty ``A`` i ``B`` są w dwuwymiarowej przestrzeni
1. Oblicz odległość między nimi wykorzystując algorytm Euklidesa
1. Funkcja musi przechodzić ``doctest``

In [ ]:
def euclidean_distance(A, B):
    """
    >>> A = (1, 0)
    >>> B = (0, 1)
    >>> euclidean_distance(A, B)
    1.4142135623730951

    >>> euclidean_distance((0,0), (1,0))
    1.0

    >>> euclidean_distance((0,0), (1,1))
    1.4142135623730951

    >>> euclidean_distance((0,1), (1,1))
    1.0

    >>> euclidean_distance((0,10), (1,1))
    9.055385138137417
    """
    x1 = A[0]
    y1 = A[1]
    x2 = B[0]
    y2 = B[1]
    
    dx = np.power(x2-x1, 2)
    dy = np.power(y2-y1, 2)
    
    return np.sqrt(dx + dy)


import doctest
doctest.testmod()

## Euclidean distance ``n`` dimensions

1. Dane są dwa punkty ``A: Sequence[int]`` i ``B: Sequence[int]``
1. Koordynaty są w systemie kartezjańskim
1. Punkty ``A`` i ``B`` są w ``N``-wymiarowej przestrzeni
1. Punkty ``A`` i ``B`` muszą być w tej samej przestrzeni
1. Oblicz odległość między nimi wykorzystując algorytm Euklidesa
1. Funkcja musi przechodzić ``doctest``

In [ ]:
def euclidean_distance(A, B):
    """
    >>> euclidean_distance((0,0,1,0,1), (1,1))
    Traceback (most recent call last):
        ...
    ValueError: Points must be in the same dimensions

    >>> A = (0,1,0,1)
    >>> B = (1,1,0,0)
    >>> euclidean_distance(A, B)
    1.4142135623730951

    >>> euclidean_distance((0,0,0), (0,0,0))
    0.0

    >>> euclidean_distance((0,0,0), (1,1,1))
    1.7320508075688772

    >>> euclidean_distance((0,1,0,1), (1,1,0,0))
    1.4142135623730951

    >>> euclidean_distance((0,0,1,0,1), (1,1,0,0,1))
    1.7320508075688772
    """
    if len(A) != len(B):
        raise ValueError('Points must be in the same dimensions')

    under_root = 0
    
    for n1, n2 in zip(A, B):
        under_root += np.power(n2-n1, 2)

    return np.sqrt(under_root)
        
    
    ## Alternative solution
    return np.sqrt(np.sum([np.power(n2-n1, 2) for n1, n2 in zip(A, B)]))


import doctest
doctest.testmod()